#
# Targetting docker-compose version 2 as it is compatible with
# docker version 1.12.  This version of docker is still widely
# used and compatible with Kubernetes.
#
version: '2'

volumes:
  elastic_search_data:

services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    volumes:
     - elastic_search_data:/usr/share/elasticsearch/data
    ports:
     - "9200:9200"
     - "9300:9300"

  kibana:
    image: kibana:latest
    container_name: kibana
    ports:
     - "5601:5601"
    links:
     - elasticsearch:elasticsearch